version: '3'
services:
  file-share-server:
    image: seungyeop-lee/file-share-server:latest
    build:
      context: ../server
    ports:
      - ${SERVER_PORT}:8080
      - ${DEBUG_PORT}:2345
    environment:
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS}
    volumes:
      - ../server:/app/file-share/server:cached
      - ../${SHARE_DIR}:/app/file-share/share_dir:cached